/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteCodeRouteImport } from './routes/invite.$code'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedFixturesRouteImport } from './routes/_authenticated.fixtures'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as ApiPublicSyncWorldcupRouteImport } from './routes/api/public/sync-worldcup'
import { Route as AuthenticatedPlayersUserIdRouteImport } from './routes/_authenticated.players.$userId'
import { Route as AuthenticatedMatchesMatchIdRouteImport } from './routes/_authenticated.matches.$matchId'
import { Route as AuthenticatedLeaguesNewRouteImport } from './routes/_authenticated.leagues.new'
import { Route as AuthenticatedLeaguesJoinRouteImport } from './routes/_authenticated.leagues.join'
import { Route as AuthenticatedLeaguesLeagueIdRouteImport } from './routes/_authenticated.leagues.$leagueId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteCodeRoute = InviteCodeRouteImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFixturesRoute = AuthenticatedFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicSyncWorldcupRoute = ApiPublicSyncWorldcupRouteImport.update({
  id: '/api/public/sync-worldcup',
  path: '/api/public/sync-worldcup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlayersUserIdRoute =
  AuthenticatedPlayersUserIdRouteImport.update({
    id: '/players/$userId',
    path: '/players/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMatchesMatchIdRoute =
  AuthenticatedMatchesMatchIdRouteImport.update({
    id: '/matches/$matchId',
    path: '/matches/$matchId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaguesNewRoute = AuthenticatedLeaguesNewRouteImport.update({
  id: '/leagues/new',
  path: '/leagues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaguesJoinRoute =
  AuthenticatedLeaguesJoinRouteImport.update({
    id: '/leagues/join',
    path: '/leagues/join',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeaguesLeagueIdRoute =
  AuthenticatedLeaguesLeagueIdRouteImport.update({
    id: '/leagues/$leagueId',
    path: '/leagues/$leagueId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fixtures': typeof AuthenticatedFixturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/invite/$code': typeof InviteCodeRoute
  '/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/leagues/join': typeof AuthenticatedLeaguesJoinRoute
  '/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/players/$userId': typeof AuthenticatedPlayersUserIdRoute
  '/api/public/sync-worldcup': typeof ApiPublicSyncWorldcupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fixtures': typeof AuthenticatedFixturesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/invite/$code': typeof InviteCodeRoute
  '/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/leagues/join': typeof AuthenticatedLeaguesJoinRoute
  '/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/players/$userId': typeof AuthenticatedPlayersUserIdRoute
  '/api/public/sync-worldcup': typeof ApiPublicSyncWorldcupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fixtures': typeof AuthenticatedFixturesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_authenticated/leagues/$leagueId': typeof AuthenticatedLeaguesLeagueIdRoute
  '/_authenticated/leagues/join': typeof AuthenticatedLeaguesJoinRoute
  '/_authenticated/leagues/new': typeof AuthenticatedLeaguesNewRoute
  '/_authenticated/matches/$matchId': typeof AuthenticatedMatchesMatchIdRoute
  '/_authenticated/players/$userId': typeof AuthenticatedPlayersUserIdRoute
  '/api/public/sync-worldcup': typeof ApiPublicSyncWorldcupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/fixtures'
    | '/profile'
    | '/invite/$code'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/leagues/new'
    | '/matches/$matchId'
    | '/players/$userId'
    | '/api/public/sync-worldcup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/fixtures'
    | '/profile'
    | '/invite/$code'
    | '/leagues/$leagueId'
    | '/leagues/join'
    | '/leagues/new'
    | '/matches/$matchId'
    | '/players/$userId'
    | '/api/public/sync-worldcup'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/fixtures'
    | '/_authenticated/profile'
    | '/invite/$code'
    | '/_authenticated/leagues/$leagueId'
    | '/_authenticated/leagues/join'
    | '/_authenticated/leagues/new'
    | '/_authenticated/matches/$matchId'
    | '/_authenticated/players/$userId'
    | '/api/public/sync-worldcup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteCodeRoute: typeof InviteCodeRoute
  ApiPublicSyncWorldcupRoute: typeof ApiPublicSyncWorldcupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fixtures': {
      id: '/_authenticated/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof AuthenticatedFixturesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/sync-worldcup': {
      id: '/api/public/sync-worldcup'
      path: '/api/public/sync-worldcup'
      fullPath: '/api/public/sync-worldcup'
      preLoaderRoute: typeof ApiPublicSyncWorldcupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/players/$userId': {
      id: '/_authenticated/players/$userId'
      path: '/players/$userId'
      fullPath: '/players/$userId'
      preLoaderRoute: typeof AuthenticatedPlayersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/matches/$matchId': {
      id: '/_authenticated/matches/$matchId'
      path: '/matches/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof AuthenticatedMatchesMatchIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues/new': {
      id: '/_authenticated/leagues/new'
      path: '/leagues/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof AuthenticatedLeaguesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues/join': {
      id: '/_authenticated/leagues/join'
      path: '/leagues/join'
      fullPath: '/leagues/join'
      preLoaderRoute: typeof AuthenticatedLeaguesJoinRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leagues/$leagueId': {
      id: '/_authenticated/leagues/$leagueId'
      path: '/leagues/$leagueId'
      fullPath: '/leagues/$leagueId'
      preLoaderRoute: typeof AuthenticatedLeaguesLeagueIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFixturesRoute: typeof AuthenticatedFixturesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedLeaguesLeagueIdRoute: typeof AuthenticatedLeaguesLeagueIdRoute
  AuthenticatedLeaguesJoinRoute: typeof AuthenticatedLeaguesJoinRoute
  AuthenticatedLeaguesNewRoute: typeof AuthenticatedLeaguesNewRoute
  AuthenticatedMatchesMatchIdRoute: typeof AuthenticatedMatchesMatchIdRoute
  AuthenticatedPlayersUserIdRoute: typeof AuthenticatedPlayersUserIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFixturesRoute: AuthenticatedFixturesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedLeaguesLeagueIdRoute: AuthenticatedLeaguesLeagueIdRoute,
  AuthenticatedLeaguesJoinRoute: AuthenticatedLeaguesJoinRoute,
  AuthenticatedLeaguesNewRoute: AuthenticatedLeaguesNewRoute,
  AuthenticatedMatchesMatchIdRoute: AuthenticatedMatchesMatchIdRoute,
  AuthenticatedPlayersUserIdRoute: AuthenticatedPlayersUserIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteCodeRoute: InviteCodeRoute,
  ApiPublicSyncWorldcupRoute: ApiPublicSyncWorldcupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
